trivy-task/.taskkey
trivy-task/index.ts
trivy-task/task.json
ui/src/App.tsx
ui/src/AssuranceTable.tsx
ui/src/BaseReport.tsx
ui/src/FilesystemReport.tsx
ui/src/ImageReport.tsx
ui/src/ReportsPane.tsx
ui/src/trivy.tsx
vss-extension.json

Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>

feat: Add assurance issues UI

---

ui/src/App.tsx

fix: allow custom display names

---

marketplace.md
trivy-task/index.ts
trivy-task/task.json

Hi, I took the liberty of opening this pull request to add a new "options" input. 
This input allow us to pass any flag to trivy like the timeout
Resolve #29

Add options input to pass any flag to trivy

---

trivy-task/index.ts

Update Trivy to version v0.45.1
re: https://github.com/aquasecurity/trivy/discussions/5258

feat: Update Trivy to version v0.45.1

---

trivy-task/index.ts

Added docker.sock mount according to recommendations in trivy documentation

Add docker.sock mount

---

marketplace.md

PR as requested here : https://github.com/aquasecurity/trivy-azure-pipelines-task/pull/25#issuecomment-1514238443

Updated doc when scanning private repository

---

.gitignore
Makefile
scripts/dev.sh
scripts/release.sh
trivy-task/.prettierrc
trivy-task/package-lock.json
trivy-task/package.json
trivy-task/task.json.tmpl
trivy-task/tsconfig.json
ui/.prettierrc
ui/package-lock.json
ui/package.json
ui/src/App.tsx
ui/src/AssuranceTable.tsx
ui/src/BaseReport.tsx
ui/src/Crash.tsx
ui/src/FilesystemReport.tsx
ui/src/ImageReport.tsx
ui/src/Loading.tsx
ui/src/MisconfigurationsTable.tsx
ui/src/ReportStats.tsx
ui/src/ReportsPane.tsx
ui/src/SecretsTable.tsx
ui/src/VulnerabilitiesTable.tsx
ui/src/index.tsx
ui/src/severity.tsx
ui/src/trivy.tsx
ui/tsconfig.json
vss-extension.dev.json.tmpl
vss-extension.json.tmpl

- **chore: prepare dev publish**
- **chore: tidy build process**

chore: tidy build process

---

marketplace.md

docs: add version example

---

trivy-task/additionalReporting.ts
trivy-task/task.json
trivy-task/trivyLoader.ts
trivy-task/utils.ts
ui/src/ReportsPane.tsx
ui/src/css/styles.css
vss-extension.dev.json

for each specified version of the trivy binary, download and call it the
versioned name so that it can be reused if already present on the agent

chore: version the trivy install so it's not repeatedly downloaded

---

trivy-task/index.ts
trivy-task/package-lock.json
ui/package-lock.json

Ensure that Trivy has created an output file before trying to create
additional reports

fix: only create additional reports when successful

---

Makefile
trivy-task/index.ts
trivy-task/task.json
trivy-task/trivyLoader.ts
vss-extension.dev.json

- Fix issue where the .docker file gets the wrong permissions
- Fix issues when using docker mode and the paths are incorrect
Resolves #103 
Resolves #34

fix: issues with file paths

---

trivy-task/index.ts
trivy-task/task.json
trivy-task/task.json.tmpl
trivy-task/trivyLoader.ts
vss-extension.dev.json

add support for overriding the trivy docker image
Resolves #20

feat: support custom trivy image

---

marketplace.md
trivy-task/additionalReporting.ts
trivy-task/index.ts
trivy-task/task.json
trivy-task/trivyLoader.ts
ui/src/BaseReport.tsx
ui/src/LicenseTable.tsx
ui/src/MisconfigurationsTable.tsx
ui/src/ReportStats.tsx
ui/src/ReportsPane.tsx
ui/src/css/styles.css
ui/src/trivy.tsx
vss-extension.dev.json

- add view to the report for license reports
- add a license table
- fix issues with the devMode on Aqua Platform
- update statistics to include license
- update documentation on how to use the Aqua credentials
- fix issue where output variables not outputting
Resolves #112 
Resolves #113

feat: Add support for showing license reports

---

ui/src/AssuranceTable.tsx
ui/src/trivy.tsx

Use the Assurance Policy title, rather than the issue title

fix: use the correct title

---

trivy-task/trivyLoader.ts

This pull request includes several updates to improve compatibility and functionality when running Trivy in a Docker environment. The most important changes include the addition of a fail-fast check for non-Linux platforms and running container with agent uid:gid.
* Added a fail-fast check to ensure Trivy runs only on Linux platforms when using Microsoft Hosted agents.
* Run container with non-root agent user by default, also adding 'docker' group Id to the container.
* Updated volume mounts and environment variables to use `/task` directory instead of `/root` for better isolation and consistency while run as root and non-root user.
* Introduced a new `dockerRunner` function to handle Docker-specific runner creation logic.
* Replaced `||` with `??` for better handling of default values in …

feat: run docker container with agent user

---

trivy-task/trivyLoader.ts

fix: run container with agent user on Linux only

---

.azuredevops/pipelines/integration.yaml
marketplace.md
package-lock.json
package.json
trivy-task/additionalReporting.ts
trivy-task/index.ts
trivy-task/installer.ts
trivy-task/package-lock.json
trivy-task/package.json
trivy-task/trivyLoader.ts
ui/package-lock.json
ui/package.json

* Added support to install/run Trivy binary on all supported platforms (Linux, MacOS, Windows)
* Added a new file `trivy-task/installer.ts` to handle the installation of the Trivy tool, including fetching the latest version and downloading the appropriate binaries for the current platform.
* Refactored `trivy-task/trivyLoader.ts` and `trivy-task/index.ts` to improve code readability and maintainability by using `path.join` for file paths and simplifying error messages.
* Simplified the `generateAdditionalReports` function in `trivy-task/additionalReporting.ts` by removing redundant parameters.
* Added a new Azure DevOps pipeline configuration file `.azuredevops/pipelines/integration.yaml` to have entry-point for integration tests.
* Updated `marketplace.md` to include agent compatibility …

feat: multi-platform support

---

.azuredevops/pipelines/integration.yaml
trivy-task/additionalReporting.ts
trivy-task/index.ts
ui/src/App.tsx

fix: artifacts upload and report download dropdown from the same job

---

trivy-task/trivyV1/index.ts
trivy-task/trivyV1/task.json
trivy-task/trivyV1/utils.ts

Don't default the type, image or path
Resolves #155

fix: fix the task for resolving image or fs

---

trivy-task/trivyV1/task.json

Syncronise the version
Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>

chore: bump version to 1.14.x

---

trivy-task/trivyV2/task.json

- Fix options input in task.json
- Added repository scan type

Update v2 inputs

---

trivy-task/trivyV1/task.json
trivy-task/trivyV2/task.json

Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>

chore: bump versions

---

trivy-task/trivyV1/additionalReporting.ts
trivy-task/trivyV2/reports.ts

Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>

chore: fix suffix for cyclone dx conversion

---

trivy-task/trivyV1/task.json
trivy-task/trivyV2/index.ts
trivy-task/trivyV2/inputs.ts
trivy-task/trivyV2/task.json

Set the default threshold to UNKNOWN so that when not explicitly set,
the lowest threshold is used

fix: need a default threshold for failure threshold
